name = "CodeAI"
uuid = "44782c38-800c-4890-a4ed-78e5222261bd"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OpenAI = "e9f21f70-7185-4079-aca2-91159181367c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
